const state={token:localStorage.getItem('prashoes_admin_token')||'',data:null,services:[]};
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const rp=v=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(v||0));
const dt=v=>v?new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'-';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function api(path,opt={}){const res=await fetch('/api/'+path,{...opt,headers:{'content-type':'application/json','authorization':state.token?'Bearer '+state.token:'',...(opt.headers||{})}});const txt=await res.text();let json=null;try{json=txt?JSON.parse(txt):null}catch{}if(!res.ok)throw new Error(json?.error||txt||'Request gagal');return json;}
function setAuthed(ok){$('#loginCard').classList.toggle('hidden',ok);$('#adminContent').classList.toggle('hidden',!ok);$('#logoutBtn').classList.toggle('hidden',!ok);}
function showMsg(id,msg,err=false){const el=$(id);if(!el)return;el.textContent=msg;el.style.color=err?'#f87171':'#facc15';}
function activate(section){$$('.nav-item').forEach(a=>a.classList.toggle('active',a.dataset.section===section));$$('.section').forEach(s=>s.classList.toggle('active',s.dataset.sectionPanel===section));if(section==='orders'){window.scrollTo({top:0,behavior:'instant'});}}
function stats(){const d=state.data;const rows=[['Pickup Request',d.stats.pickupRequests],['Order',d.stats.orders],['Member',d.stats.members],['Revenue',rp(d.stats.totalRevenue)],['Cost',rp(d.stats.totalCost)],['Profit',rp(d.stats.totalProfit)],['Pemasukan',rp(d.stats.cashIn)],['Pengeluaran',rp(d.stats.cashOut)]];$('#statsGrid').innerHTML=rows.map(r=>`<article class="stat-card"><p class="stat-label">${r[0]}</p><p class="stat-value">${r[1]}</p></article>`).join('');}
function shoeParts(value){const parts=String(value||'').split(' • ');return {type:parts[0]||'',brand:parts[1]||'',material:parts.length>3?parts[2]:'',color:parts.length>3?parts[3]:parts[2]||''};}
function shoeLabel(item){return esc(item.shoe_description||[item.shoe_type,item.shoe_brand,item.shoe_material,item.shoe_color].filter(Boolean).join(' • ')||'Sepatu');}
function itemEditor(item){const p=shoeParts(item.shoe_description);return `<div class="item-editor hidden" data-item-editor="${item.id}"><div class="field-grid two"><label>Jenis Sepatu<input data-item-field="type" value="${esc(p.type)}" placeholder="Sneakers, boots, canvas"></label><label>Merk Sepatu<input data-item-field="brand" value="${esc(p.brand)}" placeholder="Nike, Adidas, Vans"></label><label>Jenis Bahan<input data-item-field="material" value="${esc(p.material)}" placeholder="Leather, suede, canvas"></label><label>Warna Sepatu<input data-item-field="color" value="${esc(p.color)}" placeholder="Putih, hitam, coklat"></label></div><button class="primary-btn small" data-save-item="${item.id}" type="button">Simpan Item</button></div>`;}
function orderRows(rows,small=false){if(!rows?.length)return `<tr><td colspan="${small?4:5}" class="empty">Belum ada order.</td></tr>`;return rows.map(o=>{const items=o.items||[];const shoe=items.map(i=>shoeLabel(i)).join(', ')||'-';const detail=items.map(i=>`<div class="order-item-detail"><span>${shoeLabel(i)}</span><button class="ghost-btn small" data-edit-item="${i.id}" type="button">Edit Item</button>${itemEditor(i)}</div>`).join('')||'-';return small?`<tr><td><span class="code">${esc(o.order_code)}</span></td><td>${esc(o.customer_name)}</td><td><span class="badge" title="${esc(o.status)}">${esc(o.status)}</span></td><td>${shoe}</td></tr>`:`<tr><td><span class="code">${esc(o.order_code)}</span><br><small>${dt(o.created_at)}</small></td><td>${esc(o.customer_name)}<br><small>${esc(o.whatsapp_number||'Non-member')}</small></td><td>${detail}</td><td><span class="badge" title="${esc(o.status)}">${esc(o.status)}</span></td><td class="row-actions"><button class="ghost-btn small" data-open-tracking="${o.id}">Tracking</button><button class="danger-ghost small" data-delete-order="${o.id}">Hapus</button></td></tr>`}).join('');}
function cashRows(rows,small=false){if(!rows?.length)return `<tr><td colspan="${small?3:5}" class="empty">Belum ada transaksi.</td></tr>`;return rows.map(c=>small?`<tr><td>${dt(c.transaction_date)}</td><td><span class="badge ${c.transaction_type==='pemasukkan'?'green':'red'}">${esc(c.transaction_type)}</span></td><td>${rp(c.amount)}</td></tr>`:`<tr><td>${dt(c.transaction_date)}</td><td><span class="badge ${c.transaction_type==='pemasukkan'?'green':'red'}">${esc(c.transaction_type)}</span></td><td>${esc(c.description)}</td><td class="${c.transaction_type==='pemasukkan'?'money-plus':'money-minus'}">${rp(c.amount)}</td><td>${c.quantity}</td></tr>`).join('');}
function memberRows(rows){if(!rows?.length)return '<tr><td colspan="5" class="empty">Belum ada member.</td></tr>';return rows.map(m=>`<tr><td><span class="code">${esc(m.member_code)}</span></td><td>${esc(m.full_name)}</td><td>${esc(m.whatsapp_number)}</td><td>${Number(m.total_deep_clean_pairs||0)%10}/10 Deep Clean</td><td>${m.free_wash_balance||0}</td></tr>`).join('');}
function pickupRows(rows){if(!rows?.length)return '<tr><td colspan="6" class="empty">Belum ada pickup request dari website public.</td></tr>';return rows.map(p=>`<tr><td><span class="code">${esc(p.request_code||'-')}</span><br><small>${dt(p.created_at)}</small></td><td>${esc(p.full_name)}<br><small>${esc(p.whatsapp_number||'-')} ${p.email?'• '+esc(p.email):''}</small></td><td>${esc(p.pickup_address)}${p.pickup_share_url?`<br><a class="code" href="${esc(p.pickup_share_url)}" target="_blank" rel="noopener noreferrer">Buka Maps</a>`:''}</td><td>${esc(p.service_type||'-')}<br><small>${Number(p.shoe_quantity||0)} pasang ${p.is_member?'• Member':''} ${p.member_code?'• '+esc(p.member_code):''}</small></td><td><span class="badge">${esc(p.status||'Menunggu konfirmasi')}</span></td><td>${esc(p.notes||'-')}${p.promo_label?`<br><small>Promo: ${esc(p.promo_label)}</small>`:''}</td></tr>`).join('');}
function renderServices(){state.services=state.data.services||[];}
function memberByName(name){return (state.data?.members||[]).find(m=>m.full_name.toLowerCase()===String(name||'').trim().toLowerCase())||null;}
function syncMemberList(){const list=$('#memberNameList');if(list)list.innerHTML=(state.data?.members||[]).map(m=>`<option value="${esc(m.full_name)}">${esc(m.member_code)} • ${esc(m.whatsapp_number)}</option>`).join('');}
function checkMemberName(){const name=$('input[name="customerName"]')?.value||'';const member=memberByName(name);showMsg('#memberCheckMessage',member?`Member ditemukan: ${member.member_code} • ${member.whatsapp_number}`:'Nama belum terdaftar sebagai member.',!member);return member;}
function renderTracking(){const rows=state.data.orders||[];$('#trackingList').innerHTML=rows.length?rows.map(o=>`<article class="tracking-card"><div class="tracking-card-head"><div><h3>${esc(o.order_code)} — ${esc(o.customer_name)}</h3><p>${esc(o.whatsapp_number||'-')} • ${dt(o.created_at)}</p></div><span class="badge">${esc(o.status)}</span></div><div class="tracking-controls"><select data-status-order="${o.id}">${['Pesanan dibuat','Sepatu diterima','Sedang diperiksa','Proses pembersihan','Proses pengeringan','Quality check','Siap diambil','Selesai'].map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select><button class="primary-btn small" data-save-status="${o.id}">Update</button></div><div class="tracking-items">${(o.items||[]).map(i=>`<div class="tracking-item"><b>#${i.item_number} ${esc(i.shoe_description)}</b><p>${esc(i.item_status)} ${i.notes?'• '+esc(i.notes):''}</p></div>`).join('')||'<p class="muted">Belum ada item.</p>'}</div></article>`).join(''):'<div class="empty">Belum ada order untuk tracking.</div>';}
function render(){const d=state.data;stats();$('#orderCountPill').textContent=(d.orders||[]).length+' order';$('#pickupCountPill').textContent=(d.pickups||[]).length+' request';$('#cashflowCountPill').textContent=(d.cashflow||[]).length+' transaksi';$('#recentOrdersBody').innerHTML=orderRows((d.orders||[]).slice(0,6),true);$('#ordersBody').innerHTML=orderRows(d.orders,false);$('#pickupRequestsBody').innerHTML=pickupRows(d.pickups);$('#recentCashflowBody').innerHTML=cashRows((d.cashflow||[]).slice(0,7),true);$('#cashflowBody').innerHTML=cashRows(d.cashflow,false);$('#membersBody').innerHTML=memberRows(d.members);renderServices();syncMemberList();renderTracking();}
async function load(){document.body.classList.add('loading');try{state.data=await api('dashboard');setAuthed(true);render();}catch(e){setAuthed(false);if(state.token)showMsg('#loginMessage',e.message,true);}finally{document.body.classList.remove('loading');}}
async function login(e){e.preventDefault();try{const password=new FormData(e.target).get('adminPassword');const r=await api('login',{method:'POST',body:JSON.stringify({password})});state.token=r.token;localStorage.setItem('prashoes_admin_token',state.token);showMsg('#loginMessage','Login berhasil.');await load();}catch(err){showMsg('#loginMessage',err.message,true)}}
async function createOrder(e){e.preventDefault();const fd=new FormData(e.target);const member=memberByName(fd.get('customerName'));const shoeDescription=[fd.get('shoeType'),fd.get('shoeBrand'),fd.get('shoeMaterial'),fd.get('shoeColor')].filter(Boolean).join(' • ');try{await api('orders',{method:'POST',body:JSON.stringify({customerName:fd.get('customerName'),whatsappNumber:member?.whatsapp_number||'',memberId:member?.id||null,items:[{shoeDescription}]})});showMsg('#orderMessage','Sepatu masuk tersimpan.');e.target.reset();showMsg('#memberCheckMessage','');await load();}catch(err){showMsg('#orderMessage',err.message,true)}}
async function saveItem(id){const box=$(`[data-item-editor="${id}"]`);if(!box)return;const read=name=>box.querySelector(`[data-item-field="${name}"]`)?.value||'';const shoeDescription=[read('type'),read('brand'),read('material'),read('color')].filter(Boolean).join(' • ');if(!shoeDescription){alert('Minimal isi satu detail sepatu.');return}await api('order-items',{method:'PATCH',body:JSON.stringify({id,shoeDescription})});await load();}
async function createMember(e){e.preventDefault();const fd=Object.fromEntries(new FormData(e.target));try{await api('members',{method:'POST',body:JSON.stringify(fd)});showMsg('#memberMessage','Member tersimpan.');e.target.reset();await load();}catch(err){showMsg('#memberMessage',err.message,true)}}
async function createCashflow(e){e.preventDefault();const fd=Object.fromEntries(new FormData(e.target));fd.amount=+fd.amount;fd.quantity=+fd.quantity;try{await api('cashflow',{method:'POST',body:JSON.stringify(fd)});showMsg('#cashflowMessage','Transaksi tersimpan.');e.target.reset();await load();}catch(err){showMsg('#cashflowMessage',err.message,true)}}
document.addEventListener('click',async e=>{const nav=e.target.closest('.nav-item');if(nav){activate(nav.dataset.section);return}if(e.target.id==='openOrdersBtn'){activate('orders');return}if(e.target.id==='checkMemberBtn'){checkMemberName();return}const editItem=e.target.dataset.editItem;if(editItem){$(`[data-item-editor="${editItem}"]`)?.classList.toggle('hidden');return}const saveItemId=e.target.dataset.saveItem;if(saveItemId){await saveItem(saveItemId);return}const open=e.target.dataset.openTracking;if(open){activate('tracking');return}const del=e.target.dataset.deleteOrder;if(del&&confirm('Hapus order ini?')){await api('orders?id='+encodeURIComponent(del),{method:'DELETE'});await load();return}const save=e.target.dataset.saveStatus;if(save){const status=$(`[data-status-order="${save}"]`).value;await api('orders',{method:'PATCH',body:JSON.stringify({id:save,status})});await load();return}});
$('#loginForm').addEventListener('submit',login);$('#orderForm').addEventListener('submit',createOrder);$('#memberForm').addEventListener('submit',createMember);$('#cashflowForm').addEventListener('submit',createCashflow);$('#refreshBtn').addEventListener('click',load);$('#logoutBtn').addEventListener('click',()=>{state.token='';localStorage.removeItem('prashoes_admin_token');setAuthed(false)});window.addEventListener('hashchange',()=>activate(location.hash.replace('#','')||'dashboard'));activate(location.hash.replace('#','')||'dashboard');if(state.token)load();